### PR TITLE
fix: io-engine clippy warnings

### PR DESCRIPTION
**Pull request by hrudaya21**

### CODE REVIEW

**Review by dsavitskiy — APPROVED** [review]

**Review by tiagolobocastro — COMMENTED** [review]
Most if not all of these changes already exist in develop AFAICT.
You need to rebase your branch.

**Comment by hrudaya21** [comment]
> 

No changes are present after rebase. This PR can be closed ?

**Comment by tiagolobocastro** [comment]
As expected, no files changed, we can close this?

**Comment by tiagolobocastro** [comment]
> > 
> 
> No changes are present after rebase. This PR can be closed ?

Yes I think so.

**Pull request closed without merging**
